import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { getServerAuthSession } from "~/server/auth";
import { TRPCReactProvider } from "~/trpc/react";
import SessionProvider from "./_components/SessionProvider";
import NavMenu from "./_components/NavMenu";

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {

    const session = await getServerAuthSession();

    return (
        <html lang="en" className={`${GeistSans.variable}`}>
            <body>
                <SessionProvider session={session}>
                    <TRPCReactProvider>
                        <NavMenu />
                        {children}
                    </TRPCReactProvider>
                </SessionProvider>
            </body>
        </html>
    );
}
